### ISSUE TITLE
Failed to synchronize registry data from server

### ISSUE THREAD

**Issue by DeshiDesu** [rohanverma2007/Forge-Capybara#1]
![Screenshot from 2023-02-23 12-38-07](https://user-images.githubusercontent.com/120287925/220986523-3db8f9d3-dec9-4ce6-85d3-f195a4a9ad3e.png)

**Comment by rohanverma2007** [comment]
You don't have the mod installed on the server.

**Comment by rohanverma2007** [comment]
Can you please send me the log?

**Comment by DeshiDesu** [comment]
oops I missed your commentl

**Comment by DeshiDesu** [comment]
sure ill send a log

**Comment by DeshiDesu** [comment]
it didnt work last time even though I installed it on the server. Guess I was seeing things. Sorry for the trouble
